---
title: "DLA PBL"
author: "Gregory Sanders"
date: "September 12, 2017"
output: html_document
---


#Setup
```{r Setup, echo=FALSE }

require(ggplot2)
require(stringr)
require(plyr)
require(Hmisc)
require(lubridate)
library(csis360)
options(error=recover)

Path<-"K:\\2007-01 PROFESSIONAL SERVICES\\R scripts and data\\"
if (!file.exists(paste(Path,"lookups.r",sep=""))){
  Path<-"C:\\Users\\gsand_000.ALPHONSE\\Documents\\Development\\R-scripts-and-data\\"
}

source(paste(Path,"lookups.r",sep=""))
source(paste(Path,"helper.r",sep=""))

axis.text.size<-8
strip.text.size<-6
legend.text.size<-8
# table.text.size<-5.75
title.text.size<-12
geom.text.size<-3

main.text.size<-2
note.text.size<-1.40
```

#DLA read in Files Overall
```{r DLAreadInFilesOverall, echo=FALSE }
load(file="Data//DLA.Rdata")
DLAPBLscorePSC<-PBLscorePSC[PBLscorePSC$SubCustomer=="DLA",]


DLApblScore  <- read.csv(
    paste("Data\\DLA_Contract_SP_ContractPBLscoreSubCustomerProdServOffice.txt", sep = ""),
    header = TRUE, sep = "\t", dec = ".", strip.white = TRUE, row.names=NULL,
    na.strings = c("NULL","NA",""),
    stringsAsFactors = TRUE
    )

DLApblScore<-apply_lookups(Path,DLApblScore)
DLApblScore<-subset(DLApblScore,year(Fiscal.Year)>=2000&SubCustomer=="DLA")
# View(DLApblScore[is.na(DLApblScore$MajorCommandName),])
names(DLApblScore)
str(DLApblScore)

Coloration<-read.csv(
    paste(Path,"Lookups\\","lookup_coloration.csv",sep=""),
    header=TRUE, sep=",", na.strings="", dec=".", strip.white=TRUE, 
    stringsAsFactors=FALSE
    )

Coloration<-ddply(Coloration
                  , c(.(R), .(G), .(B))
                  , transform
                  , ColorRGB=as.character(
                      if(min(is.na(c(R,G,B)))) {NA} 
                      else {rgb(max(R),max(G),max(B),max=255)}
                      )
                  )

# debug(LatticePercentLineWrapper)
DLApblScore$Graph<-TRUE


DLApblScore$SubCustomer.component<-factor(DLApblScore$SubCustomer.component,
                                          levels=c("Army","Navy","Air Force","DLA",
                                                   "MDA","MilitaryHealth","Additional DoD Components"),
                                          labels=c("Army","Navy","Air Force","DLA",
                                                   "MDA","Military\nHealth","Additional\nDoD\nComponents"),
                                          ordered=TRUE)
DLApblScore$SubCustomer.component<-droplevels(DLApblScore$SubCustomer.component)


DLApblScore$SubCustomer.detail<-factor(DLApblScore$SubCustomer.detail,
                                       levels=c("Army","Navy","Air Force","DLA",
                                                "Other DoD"),
                                       labels=c("Army","Navy","Air Force","DLA",
                                                "Other DoD"),
                                       ordered=TRUE)
DLApblScore$SubCustomer.detail<-droplevels(DLApblScore$SubCustomer.detail)



DLApblScore$MaxOfIsPerformanceBasedLogistics<-factor(DLApblScore$MaxOfIsPerformanceBasedLogistics,
                                                     levels=c(0
                                                              ,1
                                                              ),
                                                     labels=c("Not PBL"
                                                              ,"All PBL"
                                                              ),
                                                     ordered=TRUE)

DLApblScore$MaxOfIsPerformanceBasedLogistics[is.na(DLApblScore$MaxOfIsPerformanceBasedLogistics)]<-"Not PBL"


DLApblScore$MaxOfIsOfficialPBL<-factor(DLApblScore$MaxOfIsOfficialPBL,
                                       exclude=NULL,
                                       levels=c(1,
                                                0,
                                                NA
                                                ),
                                       labels=c("Official PBL"
                                                ,"Other"
                                                ,"Not PBL"
                                                ),
                                       ordered=TRUE)

DLApblScore$MaxOfIsOfficialPBL[is.na(DLApblScore$MaxOfIsOfficialPBL)]<-"Not PBL"

DLApblScore$MaxOfPSCscore[is.na(DLApblScore$MaxOfPSCscore)]<-0
DLApblScore$LengthSingleScore<-DLApblScore$LengthScore+DLApblScore$MaxOfIsSingleAward
DLApblScore$LengthSingleScore[DLApblScore$LengthSingleScore==3]<-2


```










#DLA address Category
```{r DLAaddressCat}        

DLApblScore$LengthSingleScore<-DLApblScore$LengthScore+DLApblScore$MaxOfIsSingleAward
DLApblScore$LengthSingleScore[DLApblScore$LengthSingleScore==3]<-2
DLApblScore$MaxOfPSCscore[is.na(DLApblScore$MaxOfPSCscore)]<-0
DLApblScore$JointScore<-DLApblScore$LengthSingleScore+DLApblScore$PricingScore+DLApblScore$MaxOfPSCscore+DLApblScore$MaxOfIsOnlyOneSource*2
DLApblScore$JointScore[is.na(DLApblScore$JointScore)|DLApblScore$JointScore<0]<-0
DLApblScore$AddressCat<- cut2(DLApblScore$JointScore,cuts=c(4,6,9))


DLApblScore$AddressCat<-factor(DLApblScore$AddressCat,
                               #                                     exclude=NULL,
                               levels=c("[ 0, 4)",
                                        "[ 4, 6)",
                                        "[ 6, 9)",
                                        "[ 9,10]"
                                        ),
                               labels=c("No history [0-3]"
                                        ,"Outer edge [4-5]"
                                        ,"Uncommon [6-8]"
                                        ,"Promising [9-10]"
                                        ),
                               ordered=TRUE)

DLApblScore$MaxOfIsOfficialPBL[is.na(DLApblScore$MaxOfIsOfficialPBL)]<-"Not PBL"

# ggplot(#"MaxOfIsOfficialPBL"
#   data = subset(DLApblScore,MaxOfIsPerformanceBasedLogistics=="All PBL" & Fiscal.Year>=as.Date("2011-10-01")),
#   aes_string(x = "MaxOfIsPerformanceBasedLogistics", weight="pObligationJ", fill="MaxOfIsOfficialPBL"),
#   ) + geom_bar()#binwidth=1 + 
#     facet_grid( . ~ JointScore) 
# #                 scales = "free_y",
# #                 space = "free_y")+ scale_y_continuous(expand = c(0.1,0.01)) #+scale_x_continuous(limits=c(0,10))

DLApblScore<-ddply(DLApblScore, .(AddressCat), transform, pObligationA=Obligation.2014/sum(Obligation.2014))

ggplot(#"MaxOfIsOfficialPBL"
    data = subset(DLApblScore,MaxOfIsPerformanceBasedLogistics=="All PBL" & Fiscal.Year>=as.Date("2011-10-01")),
    aes_string(x = "MaxOfIsPerformanceBasedLogistics", weight="pObligationA", fill="MaxOfIsOfficialPBL"),
    ) + geom_bar()#binwidth=1 + 
    facet_grid( . ~ AddressCat) 
#                 scales = "free_y",
#                 space = "free_y")+ scale_y_continuous(expand = c(0.1,0.01)) #+scale_x_continuous(limits=c(0,10))


ggplot(#"MaxOfIsOfficialPBL"
    data = subset(DLApblScore,MaxOfIsPerformanceBasedLogistics=="All PBL" & Fiscal.Year>=as.Date("2011-10-01")),
    aes_string(x = "MaxOfIsPerformanceBasedLogistics", weight="Obligation.2014", fill="MaxOfIsOfficialPBL"),
    ) + geom_bar()#binwidth=1 + 
    facet_grid( . ~ JointScore  )#,
#                 #scales = "free_y",
#                # space = "free_y") #+ scale_y_continuous(expand = c(0,50)) +scale_x_continuous(limits=c(0,10))
# 


ggplot(#"MaxOfIsOfficialPBL"
    data = subset(DLApblScore,MaxOfIsPerformanceBasedLogistics=="All PBL" & Fiscal.Year>=as.Date("2011-10-01")),
    aes_string(x = "MaxOfIsPerformanceBasedLogistics", weight="Obligation.2014", fill="MaxOfIsOfficialPBL"),
    ) + geom_bar()#binwidth=1 + 
    facet_grid( . ~ AddressCat  )#,



ggplot(#"MaxOfIsOfficialPBL"
    data = DLApblScore,
    aes_string(x = "MaxOfIsPerformanceBasedLogistics", weight="Obligation.2014", fill="MaxOfIsOfficialPBL"),
    ) + geom_bar()#binwidth=1 + 
    facet_grid( . ~ AddressCat  )#,




```



#DLA bar Overall


```{r DLAbarOverall}  

png(
    paste( paste("Output\\DoD_components"
                 ,"DLA"
                 ,"PBL_addressable"
                 ,"Bar"
                 ,"Annual"
                 ,sep="_"
                 )
           ,".png"
           , sep=""
           )
    , type="cairo"
    , width=7.5
    , height=4
    , units='in'
    , pointsize=12
    , res=300
    )

# debug(LatticePercentLineWrapper)

PBLgraph<-LatticePlotWrapper(
    "AddressablePBL"
    ,""
    ,"Fiscal Year"
    ,"Contract Obligations, 2014 Billions"
    ,Coloration
    ,subset(DLApblScore,SubCustomer.detail=="DLA")
    ,NA
    ,"Fiscal.Year"
    ,"Obligation.2014"
    ,"AddressCat"
    ,"AddressCat"
    #     ,"USDATL"
    #     ,"StartDate"
    #     ,"EndDate"
    )
# #900 500 updat efirst bitmap
# 
# 
# PBLgraph<-PBLgraph+aes(size=y.variable)
# # PBLgraph+geom_vline(aes(xintercept=as.numeric(StartDate)))+geom_vline(aes(xintercept=as.numeric(EndDate)))
#     PBLgraph<-PBLgraph+geom_rect(aes(xmin=StartDate, xmax=EndDate, ymin=-Inf, ymax=Inf),color="red",alpha=0,size=1)
# PBLgraph<-PBLgraph+scale_y_continuous(limits=c(0,1),labels = percent_format())+
#     theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))+
#     scale_x_date(labels=date_format("'%y"),breaks=date_breaks("year"))
PBLgraph
print(PBLgraph)
#     PBLgraph+scale_fill_manual(values = alpha(c("red","blue"), .3))
dev.off()


```


#DLA bar product or service code

```{r DLAbarProdServ}  

png(
    paste( paste("Output\\DoD_components"
                 ,"DLA"
                 ,"PBL_addressable"
                 ,"Bar"
                 ,"Annual"
                 ,sep="_"
                 )
           ,".png"
           , sep=""
           )
    , type="cairo"
    , width=7.5
    , height=4
    , units='in'
    , pointsize=12
    , res=300
    )

# debug(LatticePercentLineWrapper)


DLApblScore$Graph[DLApblScore$ProductOrServiceArea=="Unlabeled"]<-FALSE
DLApblScore$Graph[DLApblScore$AddressCat=="No history [0-3]"]<-FALSE
#Flip the order to put promising on bottom.
DLApblScore$AddressCat<-factor(DLApblScore$AddressCat,rev(levels(DLApblScore$AddressCat)))


PBLgraph<-LatticePlotWrapper(
    "Addressable Market Category"
    ,"DLA Contract Spending by Product or Service Bucket \nand Addressable Market Category (No History Excluded)"
    ,"Fiscal Year"
    ,"Contract Obligations, 2014 Billions"
    ,Coloration
    ,DLApblScore
    ,NA
    ,"Fiscal.Year"
    ,"Obligation.2014"
    ,"AddressCat"
    ,"ProductOrServiceArea.DLA"
    #     ,"USDATL"
    #     ,"StartDate"
    #     ,"EndDate"
    )
# #900 500 updat efirst bitmap
# 
# 
PBLgraph<-PBLgraph+theme(legend.position="bottom")
# # PBLgraph+geom_vline(aes(xintercept=as.numeric(StartDate)))+geom_vline(aes(xintercept=as.numeric(EndDate)))
#     PBLgraph<-PBLgraph+geom_rect(aes(xmin=StartDate, xmax=EndDate, ymin=-Inf, ymax=Inf),color="red",alpha=0,size=1)
# PBLgraph<-PBLgraph+scale_y_continuous(limits=c(0,1),labels = percent_format())+
#     theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))+
#     scale_x_date(labels=date_format("'%y"),breaks=date_breaks("year"))
PBLgraph
print(PBLgraph)
#     PBLgraph+scale_fill_manual(values = alpha(c("red","blue"), .3))
dev.off()


```

#DLA product or Service PBL percent line

```{r DLAprodservPBLpercentline}        
png(
    paste( "Output\\" ,paste("DLA",
                             "ProdServ",
                             "PBL_addressable",
                             "Percent",
                             "Annual",
                             sep="_"
                             )
           ,".png"
           , sep=""
           )
    , type="cairo"
    , width=7.5
    , height=5
    , units='in'
    , pointsize=12
    , res=150
    )


DLApblScore$Graph[DLApblScore$ProductOrServiceArea=="Unlabeled"]<-FALSE
DLApblScore$Graph[DLApblScore$AddressCat=="No history [0-3]"]<-FALSE
# debug(LatticePercentLineWrapper)
PBLgraph<-LatticePercentLineWrapper(
    "Addressable PBL category"
    ,""
    ,"Fiscal Year"
    ,"% of Component Obligations"
    ,Coloration
    ,DLApblScore
    ,4
    ,"Fiscal.Year"
    ,"Obligation.2014"
    ,"AddressCat"
    ,"ProductOrServiceArea.DLA"
    #     ,"USDATL"
    #     ,"StartDate"
    #     ,"EndDate"
    )


# PBLgraph+geom_vline(aes(xintercept=as.numeric(StartDate)))+geom_vline(aes(xintercept=as.numeric(EndDate)))

PBLgraph<-PBLgraph+
    theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))+
    scale_x_date(labels=date_format("'%y"), limits=c(as.Date("2000-01-01"),as.Date("2014-10-01")),breaks=date_breaks("year"))

PBLgraph
print(PBLgraph)
#     PBLgraph+scale_fill_manual(values = alpha(c("red","blue"), .3))

dev.off()
```

#DLA mcc PBL bar

```{r DLAmccPBLbar}  

png(
    paste( paste("Output\\DoD_components"
                 ,"DLA"
                 ,"PBL_addressable"
                 ,"MajorCommand"
                 ,"Bar"
                 ,"Annual"
                 ,sep="_"
                 )
           ,".png"
           , sep=""
           )
    , type="cairo"
    , width=7.5
    , height=4
    , units='in'
    , pointsize=12
    , res=300
    )


DLApblScore<-subset(DLApblScore,SubCustomer=="DLA"&year(Fiscal.Year)>2004)
DLApblScore$Graph[DLApblScore$ProductOrServiceArea=="Unlabeled"]<-FALSE
DLApblScore$Graph[DLApblScore$AddressCat=="No history [0-3]"]<-FALSE
#Flip the order to put promising on bottom.
DLApblScore$AddressCat<-factor(DLApblScore$AddressCat,rev(levels(DLApblScore$AddressCat)))
# debug(PrepareLabelsAndColors)

# debug(LatticePlotWrapper)
PBLgraph<-LatticePlotWrapper(
    "Addressable Market Category"
    ,"DLA Contract Spending by Product or Service Bucket \nand Addressable Market Category (No History Excluded)"
    ,"Fiscal Year"
    ,"Contract Obligations, 2014 Billions"
    ,Coloration
    ,DLApblScore
    ,NA
    ,"Fiscal.Year"
    ,"Obligation.2014"
    ,"AddressCat"
    ,"MajorCommandName"#ContractingOfficeName
    #     ,"USDATL"
    #     ,"StartDate"
    #     ,"EndDate"
    )
# #900 500 updat efirst bitmap
# 
# 
PBLgraph<-PBLgraph+theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))
# # PBLgraph+geom_vline(aes(xintercept=as.numeric(StartDate)))+geom_vline(aes(xintercept=as.numeric(EndDate)))
#     PBLgraph<-PBLgraph+geom_rect(aes(xmin=StartDate, xmax=EndDate, ymin=-Inf, ymax=Inf),color="red",alpha=0,size=1)
# PBLgraph<-PBLgraph+scale_y_continuous(limits=c(0,1),labels = percent_format())+
#     theme(legend.position="bottom")+
#     scale_x_date(labels=date_format("'%y"),breaks=date_breaks("year"))
# PBLgraph<-facetAdjust(PBLgraph)
print(PBLgraph)
#     PBLgraph+scale_fill_manual(values = alpha(c("red","blue"), .3))
dev.off()


```

#DLA mcc PBL percent line
```{r DLAmccPBLpercentline}        
png(
    paste( "Output\\" ,paste("DLA",
                             "MajorCommand",
                             "PBL_addressable",
                             "Percent",
                             "Annual",
                             sep="_"
                             )
           ,".png"
           , sep=""
           )
    , type="cairo"
    , width=7.5
    , height=5
    , units='in'
    , pointsize=12
    , res=150
    )

DLApblScore<-subset(DLApblScore,SubCustomer=="DLA"&year(Fiscal.Year)>2004)
DLApblScore$Graph[DLApblScore$ProductOrServiceArea=="Unlabeled"]<-FALSE
DLApblScore$Graph[DLApblScore$AddressCat=="No history [0-3]"]<-FALSE
# debug(LatticePercentLineWrapper)
PBLgraph<-LatticePercentLineWrapper(
    "Addressable PBL category"
    ,""
    ,"Fiscal Year"
    ,"% of Component Obligations"
    ,Coloration
    ,DLApblScore
    ,4
    ,"Fiscal.Year"
    ,"Obligation.2014"
    ,"AddressCat"
    ,"MajorCommandName"
    #     ,"USDATL"
    #     ,"StartDate"
    #     ,"EndDate"
    )


# PBLgraph+geom_vline(aes(xintercept=as.numeric(StartDate)))+geom_vline(aes(xintercept=as.numeric(EndDate)))

PBLgraph<-PBLgraph+
    theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))+
    scale_x_date(labels=date_format("'%y"), limits=c(as.Date("2005-01-01"),as.Date("2014-10-01")),breaks=date_breaks("year"))

PBLgraph
print(PBLgraph)
#     PBLgraph+scale_fill_manual(values = alpha(c("red","blue"), .3))

dev.off()
```


#DLA office PBL bar by MC
```{r DLAofficePBLbarByMCC}  
#Flip the order to put promising on bottom.
# DLApblScore$AddressCat<-factor(DLApblScore$AddressCat,rev(levels(DLApblScore$AddressCat)))

for(m in unique(DLApblScore$MajorCommandName)){
    MCCpblScore<-subset(DLApblScore,year(Fiscal.Year)>2004&MajorCommandName==m)
    MCCpblScore$Graph[is.na(MCCpblScore$CSISofficeName.PBL)]<-FALSE
    MCCpblScore$Graph[MCCpblScore$AddressCat=="No history [0-3]"]<-FALSE
    if(any(MCCpblScore$Graph)){
    png(
      paste("Output\\",
                     CleanFileName(paste("DoD_components"
                                         ,"DLA"
                                         ,"PBL_addressable"
                                         ,"MajorCommand"
                                         ,m
                                         ,"Office"
                                         ,"Bar"
                                         ,"Annual"
                                         ,sep="_"
                                         ))
                                   ,".png"
                                   , sep=""
                                   )
                     , type="cairo"
                     , width=7.5
                     , height=5
                     , units='in'
                     , pointsize=12
                     , res=300
                     )
               
               # debug(LatticePercentLineWrapper)
               
#                debug(LatticePlotWrapper)
               
               PBLgraph<-LatticePlotWrapper(
                   "Addressable Market Category"
                   ,paste(m,"Contract Spending by Contracting Office \nand Addressable Market Category (No History Excluded)")
                   ,"Fiscal Year"
                   ,"Contract Obligations, 2014 Billions"
                   ,Coloration
                   ,MCCpblScore
                   ,4
                   ,"Fiscal.Year"
                   ,"Obligation.2014"
                   ,"AddressCat"
                   ,"CSISofficeName.PBL"
#                    ,"MajorCommandName"
                   #     ,"StartDate"
                   #     ,"EndDate"
,DataLabels=FALSE
                   )
               # #900 500 updat efirst bitmap
               # 
               # 
               PBLgraph<-PBLgraph+theme(legend.position="bottom")+
    theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))
#     PBLgraph<-PBLgraph+facet_wrap(MajorCommandName~ContractingOfficeName)
               # # PBLgraph+geom_vline(aes(xintercept=as.numeric(StartDate)))+geom_vline(aes(xintercept=as.numeric(EndDate)))
               #     PBLgraph<-PBLgraph+geom_rect(aes(xmin=StartDate, xmax=EndDate, ymin=-Inf, ymax=Inf),color="red",alpha=0,size=1)
               # PBLgraph<-PBLgraph+scale_y_continuous(limits=c(0,1),labels = percent_format())+
               #     theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))+
               #     scale_x_date(labels=date_format("'%y"),breaks=date_breaks("year"))
               PBLgraph
               print(PBLgraph)
               #     PBLgraph+scale_fill_manual(values = alpha(c("red","blue"), .3))
               dev.off()
               }
    }

```



#DLA office PBL percent line
```{r DLAofficePBLPercentLine}  
#Flip the order to put promising on bottom.
# DLApblScore$AddressCat<-factor(DLApblScore$AddressCat,rev(levels(DLApblScore$AddressCat)))

for(m in unique(DLApblScore$MajorCommandName)){
    MCCpblScore<-subset(DLApblScore,year(Fiscal.Year)>2004&MajorCommandName==m)
    MCCpblScore$Graph[is.na(MCCpblScore$CSISofficeName.PBL)]<-FALSE
    MCCpblScore$Graph[MCCpblScore$AddressCat=="No history [0-3]"]<-FALSE
    if(any(MCCpblScore$Graph)){
        

    png(
      paste("Output\\",
                     CleanFileName(paste("DoD_components"
                                         ,"DLA"
                                         ,"PBL_addressable"
                                         ,"MajorCommand"
                                         ,m
                                         ,"Office"
                                         ,"Percent"
                                         ,"Annual"
                                         ,sep="_"
                                         ))
                                   ,".png"
                                   , sep=""
                                   )
                     , type="cairo"
                     , width=7.5
                     , height=5
                     , units='in'
                     , pointsize=12
                     , res=300
                     )
               
               # debug(LatticePercentLineWrapper)
               
#                debug(LatticePlotWrapper)
               
        
        
# debug(LatticePercentLineWrapper)
PBLgraph<-LatticePercentLineWrapper(
    "Addressable PBL category"
    ,""
    ,"Fiscal Year"
    ,"% of Component Obligations"
    ,Coloration
    ,MCCpblScore
    ,4
    ,"Fiscal.Year"
    ,"Obligation.2014"
    ,"AddressCat"
    ,"CSISofficeName.PBL"
    #     ,"USDATL"
    #     ,"StartDate"
    #     ,"EndDate"
    )


# PBLgraph+geom_vline(aes(xintercept=as.numeric(StartDate)))+geom_vline(aes(xintercept=as.numeric(EndDate)))

PBLgraph<-PBLgraph+
    theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))+
    scale_x_date(labels=date_format("'%y"), limits=c(as.Date("2005-01-01"),as.Date("2014-10-31")),breaks=date_breaks("year"))
               # #900 500 updat efirst bitmap
               # 
               # 
               
#     PBLgraph<-PBLgraph+facet_wrap(MajorCommandName~ContractingOfficeName)
               # # PBLgraph+geom_vline(aes(xintercept=as.numeric(StartDate)))+geom_vline(aes(xintercept=as.numeric(EndDate)))
               #     PBLgraph<-PBLgraph+geom_rect(aes(xmin=StartDate, xmax=EndDate, ymin=-Inf, ymax=Inf),color="red",alpha=0,size=1)
               # PBLgraph<-PBLgraph+scale_y_continuous(limits=c(0,1),labels = percent_format())+
               #     theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))+
               #     scale_x_date(labels=date_format("'%y"),breaks=date_breaks("year"))
               PBLgraph
               print(PBLgraph)
               #     PBLgraph+scale_fill_manual(values = alpha(c("red","blue"), .3))
               dev.off()
               }
    }

```

#DLA bar product by MCC
```{r DLAbarproductsbyMCC}  
for(m in unique(DLApblScore$MajorCommandName)){
    MCCpblScore<-subset(DLApblScore,year(Fiscal.Year)>2004&MajorCommandName==m)
    MCCpblScore$Graph[is.na(MCCpblScore$CSISofficeName.PBL)]<-FALSE
    MCCpblScore$Graph[MCCpblScore$AddressCat=="No history [0-3]"]<-FALSE
    if(any(MCCpblScore$Graph)){

png(
    paste( paste("Output\\DoD_components"
                 ,"DLA"
                 ,m
                 
                 ,"PBL_addressable"
                 ,"Bar"
                 ,"Annual"
                 ,sep="_"
                 )
           ,".png"
           , sep=""
           )
    , type="cairo"
    , width=7.5
    , height=4
    , units='in'
    , pointsize=12
    , res=300
    )

# debug(LatticePercentLineWrapper)

#Flip the order to put promising on bottom.
# MCCpblScore$AddressCat<-factor(MCCpblScore$AddressCat,rev(levels(MCCpblScore$AddressCat)))

#View(unique(subset(MCCpblScore, select=c("MajorCommandName","ContractingOfficeName"))))
PBLgraph<-LatticePlotWrapper(
    "Addressable Market Category"
    ,paste(m,"Contract Spending by Product or Service Bucket \nand Addressable Market Category (No History Excluded)")
    ,"Fiscal Year"
    ,"Contract Obligations, 2014 Billions"
    ,Coloration
    ,MCCpblScore
    ,NA
    ,"Fiscal.Year"
    ,"Obligation.2014"
    ,"AddressCat"
    ,"ProductOrServiceArea.DLA"
    #     ,"USDATL"
    #     ,"StartDate"
    #     ,"EndDate"
    )
# #900 500 updat efirst bitmap
# 
# 
PBLgraph<-PBLgraph+theme(legend.position="bottom")+scale_x_date(labels=date_format("'%y"),breaks=date_breaks("year"))
# # PBLgraph+geom_vline(aes(xintercept=as.numeric(StartDate)))+geom_vline(aes(xintercept=as.numeric(EndDate)))
#     PBLgraph<-PBLgraph+geom_rect(aes(xmin=StartDate, xmax=EndDate, ymin=-Inf, ymax=Inf),color="red",alpha=0,size=1)
# PBLgraph<-PBLgraph+scale_y_continuous(limits=c(0,1),labels = percent_format())+
#     theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))+
#     scale_x_date(labels=date_format("'%y"),breaks=date_breaks("year"))
PBLgraph
print(PBLgraph)
#     PBLgraph+scale_fill_manual(values = alpha(c("red","blue"), .3))
dev.off()
}
}
```



#DLA bar products
```{r DLAbarproducts}  
png(
    paste( paste("Output\\DoD_components"
                 ,"DLA"
                 ,"PBL_addressable"
                 ,"Bar"
                 ,"Annual"
                 ,sep="_"
                 )
           ,".png"
           , sep=""
           )
    , type="cairo"
    , width=7.5
    , height=4
    , units='in'
    , pointsize=12
    , res=300
    )

# debug(LatticePercentLineWrapper)

DLApblScore<-subset(DLApblScore,SubCustomer=="DLA")
DLApblScore$Graph[DLApblScore$ProductOrServiceArea=="Unlabeled"]<-FALSE
DLApblScore$Graph[DLApblScore$AddressCat=="No history [0-3]"]<-FALSE
#Flip the order to put promising on bottom.
DLApblScore$AddressCat<-factor(DLApblScore$AddressCat,rev(levels(DLApblScore$AddressCat)))

#View(unique(subset(DLApblScore, select=c("MajorCommandName","ContractingOfficeName"))))
PBLgraph<-LatticePlotWrapper(
    "Addressable Market Category"
    ,"DLA Contract Spending by Product or Service Bucket \nand Addressable Market Category (No History Excluded)"
    ,"Fiscal Year"
    ,"Contract Obligations, 2014 Billions"
    ,Coloration
    ,DLApblScore
    ,NA
    ,"Fiscal.Year"
    ,"Obligation.2014"
    ,"AddressCat"
    ,"ProductOrServiceArea.DLA"
    #     ,"USDATL"
    #     ,"StartDate"
    #     ,"EndDate"
    )
# #900 500 updat efirst bitmap
# 
# 
PBLgraph<-PBLgraph+theme(legend.position="bottom")
# # PBLgraph+geom_vline(aes(xintercept=as.numeric(StartDate)))+geom_vline(aes(xintercept=as.numeric(EndDate)))
#     PBLgraph<-PBLgraph+geom_rect(aes(xmin=StartDate, xmax=EndDate, ymin=-Inf, ymax=Inf),color="red",alpha=0,size=1)
# PBLgraph<-PBLgraph+scale_y_continuous(limits=c(0,1),labels = percent_format())+
#     theme(legend.position="bottom",axis.text.x = element_text(angle = 90, hjust = 1))+
#     scale_x_date(labels=date_format("'%y"),breaks=date_breaks("year"))
PBLgraph
print(PBLgraph)
#     PBLgraph+scale_fill_manual(values = alpha(c("red","blue"), .3))
dev.off()

```



#DLA Data Tables

```{r DLA Data Tables}

DLAscoreTablePSC<-ddply(DLApblScore, c("Fiscal.Year"
                                 ,"Customer"
                                 ,"SubCustomer"
                                 ,"AddressCat"
#                                  ,"MajorCommandName"
                                 ,"ProductOrServiceArea"
                                 ,"ProductOrServiceCode"
                                 ,"ProductOrServiceCodeText"
                                 )
                     ,summarise
                     ,Obligation.2014=sum(Obligation.2014)
                     )


DLAscoreTablePSC<-subset(DLAscoreTablePSC,SubCustomer=="DLA" & Fiscal.Year>=as.Date("2013-09-30"))

#View(DLAscoreTablePSC)


write.csv(DLAscoreTablePSC,paste(paste("Output\\DLA_addressable"
                                    ,"Obligation_2014"
                                    ,"ProductOrServiceCode"
                                    ,"2012-2014"
                                    ,sep="_"
                                    )
                              ,".csv",
                              sep=""))



DLAscoreTableMCC<-ddply(DLApblScore, c("Fiscal.Year"
                                 ,"Customer"
                                 ,"SubCustomer"
                                 ,"AddressCat"
                                 ,"MajorCommandName"
                                 ,"ProductOrServiceArea"
#                                  ,"ProductOrServiceCode"
#                                  ,"ProductOrServiceCodeText"
                                 )
                     ,summarise
                     ,Obligation.2014=sum(Obligation.2014)
                     )


DLAscoreTableMCC<-subset(DLAscoreTableMCC,SubCustomer=="DLA" & Fiscal.Year>=as.Date("2013-09-30"))

#View(DLAscoreTableMCC)


write.csv(DLAscoreTableMCC,paste(paste("Output\\DLA_addressable"
                                    ,"Obligation_2014"
                                    ,"MajorCommandName"
                                    ,"2012-2014"
                                    ,sep="_"
                                    )
                              ,".csv",
                              sep=""))

# 
# CompPolicyTable<-ddply(CompPolicy, c("Fiscal.Year"
#     ,"Competition.sum"
#     ,"SubCustomer.component"
#     ,"ATLpolicy")
#     ,summarise
#     ,Obligation.2014=sum(Obligation.2014)
# )
# write.csv(CompPolicyTable,paste(paste("DoD_components"
#                  ,"Obligation_2014"
#                  ,"Competition_sum
#                  ,"ATLpolicy"
#                  ,"Annual"
#                  ,sep="_"
#                  )
#            ,".csv",
#            sep=""))
# 

```
